-- Migration 002: Security e storage — NON RILAVANTE in single-user mode
-- L'app non usa autenticazione. RLS disabilitato, nessun bucket storage.
-- Le immagini sono URL esterni nella colonna image_url.
-- Vedi migration 003 per i dettagli della configurazione single-user.
